# Generated by Django 6.0.6 on 2026-06-27 02:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='endereço'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to=core.models.tenant_cover_path, validators=[core.models.validate_image_file], verbose_name='capa (foto)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='description',
            field=models.TextField(blank=True, max_length=600, verbose_name='descrição'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='hours',
            field=models.TextField(blank=True, max_length=400, verbose_name='horário de funcionamento'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='instagram',
            field=models.CharField(blank=True, max_length=60, verbose_name='instagram (handle)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=core.models.tenant_logo_path, validators=[core.models.validate_image_file], verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='telefone de contato'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tagline',
            field=models.CharField(blank=True, max_length=120, verbose_name='slogan'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='whatsapp'),
        ),
    ]
