# Generated by Django 6.0.6 on 2026-06-27 03:03

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_address_tenant_cover_tenant_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('bio', models.CharField(blank=True, max_length=300, verbose_name='biografia')),
                ('photo', models.FileField(blank=True, null=True, upload_to=core.models.professional_photo_path, validators=[core.models.validate_image_file], verbose_name='foto')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant', verbose_name='barbearia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'profissional',
                'verbose_name_plural': 'profissionais',
            },
            managers=[
                ('objects', core.models.TenantOwnedManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.professional', verbose_name='profissional')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.service', verbose_name='serviço')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant', verbose_name='barbearia')),
            ],
            options={
                'verbose_name': 'vínculo profissional × serviço',
                'verbose_name_plural': 'vínculos profissional × serviço',
            },
            managers=[
                ('objects', core.models.TenantOwnedManager()),
            ],
        ),
        migrations.AddField(
            model_name='professional',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='professionals', through='core.ProfessionalService', through_fields=('professional', 'service'), to='core.service', verbose_name='serviços'),
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('weekday', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')], verbose_name='dia da semana')),
                ('start_time', models.TimeField(verbose_name='início')),
                ('end_time', models.TimeField(verbose_name='fim')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.professional', verbose_name='profissional')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant', verbose_name='barbearia')),
            ],
            options={
                'verbose_name': 'disponibilidade (horário)',
                'verbose_name_plural': 'disponibilidades (horários)',
                'ordering': ('professional', 'weekday', 'start_time'),
            },
            managers=[
                ('objects', core.models.TenantOwnedManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='professionalservice',
            constraint=models.UniqueConstraint(fields=('tenant', 'professional', 'service'), name='unique_prof_service_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='professional',
            constraint=models.UniqueConstraint(fields=('tenant', 'user'), name='unique_professional_user_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='workschedule',
            constraint=models.UniqueConstraint(fields=('tenant', 'professional', 'weekday', 'start_time'), name='unique_workslot_per_tenant_pro_weekday_start'),
        ),
    ]
