# Generated by Django 6.0.6 on 2026-06-27 04:07

import core.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_professional_professionalservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('weekday', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')], verbose_name='dia da semana')),
                ('is_open', models.BooleanField(default=False, verbose_name='aberto?')),
                ('open_time', models.TimeField(default=datetime.time(8, 0), verbose_name='abertura')),
                ('close_time', models.TimeField(default=datetime.time(18, 0), verbose_name='fechamento')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='início do intervalo')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='fim do intervalo')),
            ],
            options={
                'verbose_name': 'horário de funcionamento',
                'verbose_name_plural': 'horários de funcionamento',
                'ordering': ('weekday',),
            },
            managers=[
                ('objects', core.models.TenantOwnedManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('weekday', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')], verbose_name='dia da semana')),
                ('available', models.BooleanField(default=False, verbose_name='disponível?')),
                ('start_time', models.TimeField(default=datetime.time(8, 0), verbose_name='início')),
                ('end_time', models.TimeField(default=datetime.time(18, 0), verbose_name='fim')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='início do intervalo')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='fim do intervalo')),
            ],
            options={
                'verbose_name': 'disponibilidade do profissional',
                'verbose_name_plural': 'disponibilidades dos profissionais',
                'ordering': ('professional', 'weekday'),
            },
            managers=[
                ('objects', core.models.TenantOwnedManager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='workschedule',
            name='unique_workslot_per_tenant_pro_weekday_start',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='hours',
        ),
        migrations.AddField(
            model_name='businesshours',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='core.tenant', verbose_name='barbearia'),
        ),
        migrations.AddField(
            model_name='professionalavailability',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='core.professional', verbose_name='profissional'),
        ),
        migrations.AddField(
            model_name='professionalavailability',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant', verbose_name='barbearia'),
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='professional',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='tenant',
        ),
        migrations.AddConstraint(
            model_name='businesshours',
            constraint=models.UniqueConstraint(fields=('tenant', 'weekday'), name='unique_business_hours_per_tenant_weekday'),
        ),
        migrations.AddConstraint(
            model_name='professionalavailability',
            constraint=models.UniqueConstraint(fields=('tenant', 'professional', 'weekday'), name='unique_proavailability_per_tenant_pro_weekday'),
        ),
        migrations.DeleteModel(
            name='WorkSchedule',
        ),
    ]
