# Generated by Django 6.0.6 on 2026-06-29 13:18

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_businesshours_professionalavailability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profiles', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.CreateModel(
            name='ProfessionalInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('pending', 'Aguardando aprovacao'), ('accepted', 'Aceito'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='status')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='respondido em')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_professional_invitations', to=settings.AUTH_USER_MODEL, verbose_name='convidado por')),
                ('professional_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_invitations', to=settings.AUTH_USER_MODEL, verbose_name='profissional convidado')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant', verbose_name='barbearia')),
            ],
            options={
                'verbose_name': 'convite de profissional',
                'verbose_name_plural': 'convites de profissionais',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('tenant', 'professional_user'), name='unique_pending_professional_invitation')],
            },
            managers=[
                ('objects', core.models.TenantOwnedManager()),
            ],
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('role', models.CharField(choices=[('owner', 'Dono'), ('manager', 'Gerente'), ('professional', 'Profissional')], max_length=20, verbose_name='perfil')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant', verbose_name='barbearia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'vinculo usuario x barbearia',
                'verbose_name_plural': 'vinculos usuario x barbearia',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'user', 'role'), name='unique_tenant_membership_user_role')],
            },
            managers=[
                ('objects', core.models.TenantOwnedManager()),
            ],
        ),
    ]
