# Generated by Django 6.0.6 on 2026-06-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_professional_user_professionalinvitation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(choices=[(30, '30 minutos'), (60, '60 minutos'), (90, '90 minutos'), (120, '120 minutos')], default=30, verbose_name='duração (min)'),
        ),
    ]
