# Generated by Django 6.0.6 on 2026-07-02 14:19

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_service_duration_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('client_name', models.CharField(max_length=120, verbose_name='nome do cliente')),
                ('client_phone', models.CharField(max_length=20, verbose_name='telefone')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('date', models.DateField(verbose_name='data')),
                ('start_time', models.TimeField(verbose_name='inicio')),
                ('end_time', models.TimeField(verbose_name='fim')),
                ('status', models.CharField(choices=[('pending', 'Aguardando confirmacao'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('completed', 'Concluido')], default='pending', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.professional', verbose_name='profissional')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.service', verbose_name='servico')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant', verbose_name='barbearia')),
            ],
            options={
                'verbose_name': 'agendamento',
                'verbose_name_plural': 'agendamentos',
                'ordering': ('-date', '-start_time'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('tenant', 'professional', 'date', 'start_time'), name='unique_active_appointment_per_slot')],
            },
            managers=[
                ('objects', core.models.TenantOwnedManager()),
            ],
        ),
    ]
