# Generated by Django 6.0.6 on 2026-07-03 19:46

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_appointment_endtime_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preco')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='custo')),
                ('category', models.CharField(blank=True, max_length=60, verbose_name='categoria')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant', verbose_name='barbearia')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
            },
            managers=[
                ('objects', core.models.TenantOwnedManager()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('client_name', models.CharField(max_length=120, verbose_name='nome do cliente')),
                ('client_phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('status', models.CharField(choices=[('in_progress', 'Em andamento'), ('completed', 'Concluido'), ('cancelled', 'Cancelado')], default='in_progress', max_length=20, verbose_name='status')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor total')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='iniciado em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='fechado em')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.appointment', verbose_name='agendamento')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.professional', verbose_name='profissional')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant', verbose_name='barbearia')),
            ],
            options={
                'verbose_name': 'sessao',
                'verbose_name_plural': 'sessoes',
                'ordering': ('-started_at',),
            },
            managers=[
                ('objects', core.models.TenantOwnedManager()),
            ],
        ),
        migrations.CreateModel(
            name='SessionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preco unitario')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.product', verbose_name='produto')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.session', verbose_name='sessao')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant', verbose_name='barbearia')),
            ],
            options={
                'verbose_name': 'item de sessao',
                'verbose_name_plural': 'itens de sessao',
            },
            managers=[
                ('objects', core.models.TenantOwnedManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_product_name_per_tenant'),
        ),
    ]
