# Generated by Django 6.0.6 on 2026-07-03 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_product_session_sessionproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='preço'),
        ),
        migrations.AddField(
            model_name='session',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.service', verbose_name='serviço'),
        ),
        migrations.AddField(
            model_name='session',
            name='service_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='preço do serviço'),
        ),
    ]
