# Generated by Django 6.0.6 on 2026-07-04 00:50

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_service_price_session_service_session_service_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('payment_method', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('debito', 'Débito'), ('credito', 'Crédito')], max_length=20, verbose_name='forma de pagamento')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='pago em')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='confirmado por')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.session', verbose_name='sessao')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant', verbose_name='barbearia')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
            },
            managers=[
                ('objects', core.models.TenantOwnedManager()),
            ],
        ),
    ]
