# Generated by Django 6.0.6 on 2026-07-05 01:40

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_product_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('quantity', models.IntegerField(verbose_name='quantidade')),
                ('movement_type', models.CharField(choices=[('consumption', 'Consumo em atendimento'), ('restock', 'Abastecimento'), ('adjustment', 'Ajuste manual')], max_length=20, verbose_name='tipo')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descricao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='core.product', verbose_name='produto')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.session', verbose_name='sessao')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant', verbose_name='barbearia')),
            ],
            options={
                'verbose_name': 'movimentacao de estoque',
                'verbose_name_plural': 'movimentacoes de estoque',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', core.models.TenantOwnedManager()),
            ],
        ),
    ]
