# Generated by Django 6.0.6 on 2026-07-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_stockmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Em analise'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('completed', 'Concluido')], default='pending', max_length=20, verbose_name='status'),
        ),
    ]
